In [29]:
# Understanding Tensor and its concepts

In [30]:
import tensorflow as tf
import numpy as np

In [31]:
tf.version.VERSION

'2.12.0'

In [32]:
rank_0_tensor = tf.constant(4)  # constant
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [33]:
r_1_tensor = tf.constant([2.0,3.0,4.0])  # vector
r_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [34]:
r_2_tensor = tf.constant([[2.0,3.0,4.0],[3.0,4.0,5.0]])   # matrix (2x3)
r_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [3., 4., 5.]], dtype=float32)>

In [35]:
r_3_tensor = tf.constant([[[2.0,3.0,4.0, 1.6],[3.0,4.0,5.0, 9.0]],
                          [[3.0,3.0,1.0, 7.2],[6.0,4.0,1.0, 3.0]],
                          [[5.0,9.0,8.0,6.2],[7.0,8.0,5.0, 4.0]]])
r_3_tensor   # 3-dimensional matrix : (3x2x4)

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[2. , 3. , 4. , 1.6],
        [3. , 4. , 5. , 9. ]],

       [[3. , 3. , 1. , 7.2],
        [6. , 4. , 1. , 3. ]],

       [[5. , 9. , 8. , 6.2],
        [7. , 8. , 5. , 4. ]]], dtype=float32)>

In [36]:
r_3_tensor.numpy().shape, np.array(r_3_tensor)   # converting tensor to numpy array

((3, 2, 4),
 array([[[2. , 3. , 4. , 1.6],
         [3. , 4. , 5. , 9. ]],
 
        [[3. , 3. , 1. , 7.2],
         [6. , 4. , 1. , 3. ]],
 
        [[5. , 9. , 8. , 6.2],
         [7. , 8. , 5. , 4. ]]], dtype=float32))

In [37]:
# Tensors can chave data types of int, float string and complex numbers
# The base tf.Tensor class requires tensors to be "rectangular"---that is,
# along each axis, every element is the same size.

In [38]:
# basic maths operation using tensors
a = tf.constant([[2.0,3.0],[3.0,4.0]])
b = tf.constant([[4.0,6.0],[1.0,5.0]])

In [39]:
tf.add(a, b, name="Sum")  # sum  : a + b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6., 9.],
       [4., 9.]], dtype=float32)>

In [40]:
tf.multiply(a,b,name="multiply")  # element-wise multiplication  : a * b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 8., 18.],
       [ 3., 20.]], dtype=float32)>

In [41]:
tf.matmul(a,b,name="matrix_multiplication")   # matrix multiplication : a @ b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[11., 27.],
       [16., 38.]], dtype=float32)>

In [42]:
# Other tensor operations (Ops)
c = b @ a

print(c)
# Find the total sum
print(tf.reduce_sum(c))

# Find the largest value
print(tf.reduce_max(c))

# Find the index of the largest value
print(tf.math.argmin(c))

# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(
[[26. 36.]
 [17. 23.]], shape=(2, 2), dtype=float32)
tf.Tensor(102.0, shape=(), dtype=float32)
tf.Tensor(36.0, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor(
[[4.5397868e-05 9.9995458e-01]
 [2.4726235e-03 9.9752742e-01]], shape=(2, 2), dtype=float32)


In [43]:
# Tensors have shapes. Some vocabulary:

# 1. Shape: The length (number of elements) of each of the axes of a tensor.
# 2. Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
# 3. Axis or Dimension: A particular dimension of a tensor.
# 4. Size: The total number of items in the tensor, the product of the shape vector's elements.

rank_4_tensor = tf.zeros([3, 2, 4, 5], dtype=tf.int8)
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'int8'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


In [44]:
"""
But note that the Tensor.ndim and Tensor.shape attributes don't return Tensor objects.
If you need a Tensor use the tf.rank or tf.shape function. This difference is subtle,
but it can be important when building graphs (later).
"""
tf.rank(rank_4_tensor), tf.shape(rank_4_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>)

In [45]:
# Often axes are ordered from global to local: The batch axis first, followed
# by spatial dimensions, and features for each location last.
# batch - 3 (axis = 0), height - 2(axis = 1), width - 4(axis = 2), features - 5(axis = 3 or -1)  => [3, 2, 4 5]

In [46]:
# Single-axis indexing: TensorFlow follows standard Python indexing rules, similar
# to indexing a list or a string in Python
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 34, 39, 67])
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 67


In [47]:
# Higher rank tensors are indexed by passing multiple indices.
#The exact same rules as in the single-axis case apply to each axis independently.
print(r_3_tensor)
print(r_3_tensor[:, :, 1])

tf.Tensor(
[[[2.  3.  4.  1.6]
  [3.  4.  5.  9. ]]

 [[3.  3.  1.  7.2]
  [6.  4.  1.  3. ]]

 [[5.  9.  8.  6.2]
  [7.  8.  5.  4. ]]], shape=(3, 2, 4), dtype=float32)
tf.Tensor(
[[3. 4.]
 [3. 4.]
 [9. 8.]], shape=(3, 2), dtype=float32)


In [48]:
# Manipulating Shapes

## The tf.reshape operation is fast and cheap as the underlying data does not need to be duplicated.
# TensorFlow, like many other programming languages and libraries, uses a memory
# ordering convention known as "row-major" or "C-style" memory ordering. This convention
# specifies how the elements of a multi-dimensional array are laid out in memory.

In [49]:
x = tf.constant([[5], [9], [3]])
print(x.shape)

(3, 1)


In [50]:
tf.reshape(x, shape=[1,3])


<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 9, 3]], dtype=int32)>

In [51]:
# If you flatten a tensor you can see what order it is laid out in memory.
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(r_3_tensor, [-1]))

tf.Tensor(
[2.  3.  4.  1.6 3.  4.  5.  9.  3.  3.  1.  7.2 6.  4.  1.  3.  5.  9.
 8.  6.2 7.  8.  5.  4. ], shape=(24,), dtype=float32)


In [52]:
# Typically the only reasonable use of tf.reshape is to combine or split adjacent
# axes (or add/remove 1s).
# e.g : 3x2x5  => 6x5, 3x10, 30
print(tf.reshape(r_3_tensor, [3, -1]))  # 3 x 8

tf.Tensor(
[[2.  3.  4.  1.6 3.  4.  5.  9. ]
 [3.  3.  1.  7.2 6.  4.  1.  3. ]
 [5.  9.  8.  6.2 7.  8.  5.  4. ]], shape=(3, 8), dtype=float32)


In [53]:
# Note: Reshaping will "work" for any new shape with the same total number of elements,
# but it will not do anything useful if you do not respect the order of the axes.
# For Swapping axes, you need tf.transpose rather than tf.reshape.

In [54]:
# Data types for Tensors in TensorFlow
"""
When creating a tf.Tensor from a Python object you may optionally specify the datatype.
By Default, TensorFlow chooses a datatype that can represent your data. TensorFlow
converts Python integers to tf.int32 and Python floating point numbers to tf.float32.
"""

'\nWhen creating a tf.Tensor from a Python object you may optionally specify the datatype.\nBy Default, TensorFlow chooses a datatype that can represent your data. TensorFlow \nconverts Python integers to tf.int32 and Python floating point numbers to tf.float32.\n'

In [55]:
# Broadcasting in Tensors
# Under certain conditions, smaller tensors are "stretched" automatically to fit
# larger tensors when running combined operations on them.
z = tf.constant([[2], [2], [2]])
tf.multiply(x, 2), tf.multiply(x,z)    # both operation are same

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[10],
        [18],
        [ 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[10],
        [18],
        [ 6]], dtype=int32)>)

In [56]:
# Most of the time, broadcasting is both time and space efficient, as the broadcast
# operation never materializes the expanded tensors in memory.
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3])) # braoadcast tensor to given shape

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [57]:
# Converting normal arguments to tensors
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [60]:
# Ragged Tensors
# A tensor with variable numbers of elements along some axis is called "ragged".
"""
Ragged tensors are the TensorFlow equivalent of nested variable-length lists.
They make it easy to store and process data with non-uniform shapes
"""

# ragged_tensor = tf.constant([[1, 2, 3],[5, 4],[8]])
# if we run above example, we will get following error:
""" ValueError: Can't convert non-rectangular Python sequence to Tensor. """

In [96]:
# We should use ragged tensor for such scenarios:
ragged = tf.ragged.constant([[1, 2, 3],[5, 4],[8],[9, 7], []])
print(ragged)
print(ragged.shape)  # give "None" for variable length axis
print(ragged.bounding_shape()) # give tight bounding shape=> max_dimen along each axis

<tf.RaggedTensor [[1, 2, 3], [5, 4], [8], [9, 7], []]>
(5, None)
tf.Tensor([5 3], shape=(2,), dtype=int64)


In [87]:
# Different ways of making ragged tensors:
# 1. tf.RaggedTensor.from_value_rowids
ragged_1 = tf.RaggedTensor.from_value_rowids(values=[1, 2, 3, 5, 4, 9, 6, 7 ], value_rowids=[0,0,0,1,1,3,4,4])
ragged_1 # add row index for each elements to be ragged

<tf.RaggedTensor [[1, 2, 3], [5, 4], [], [9], [6, 7]]>

In [90]:
# 2. tf.RaggedTensor.from_row_lengths
ragged_2 = tf.RaggedTensor.from_row_lengths(values=[1, 2, 3, 5, 4, 9, 6, 7 ], row_lengths=[3,2,0,3])
ragged_2 # add row length where each elements to be ragged

<tf.RaggedTensor [[1, 2, 3], [5, 4], [], [9, 6, 7]]>

In [92]:
# 3. tf.RaggedTensor.from_row_splits
ragged_3 = tf.RaggedTensor.from_row_splits(values=[1, 2, 3, 5, 4, 9, 6, 7 ], row_splits=[0,3,4,4,8])
ragged_3 # If you know the index where each row starts and ends.=> [start, end)

<tf.RaggedTensor [[1, 2, 3], [5], [], [4, 9, 6, 7]]>

In [94]:
# limitations of data types to be stored
"""
As with normal Tensors, the values in a RaggedTensor must all have the same type;
and the values must all be at the same nesting depth (the rank of the tensor)
"""

tf.Tensor([2 3], shape=(2,), dtype=int64)


In [69]:
# Operations on Ragged Tensors
"""
Ragged tensors are supported by more than a hundred TensorFlow operations, including
1. math operations (such as tf.add and tf.reduce_mean)
2. array operations (such as tf.concat and tf.tile)
3. string manipulation ops (such as tf.strings.substr)
4. control flow operations (such as tf.while_loop and tf.map_fn),
 and many others.
"""

word_ragged = tf.ragged.constant([["So", "long"], ["thanks", "for", "your", "food", "fish"], []])

print(ragged)
print(word_ragged)

<tf.RaggedTensor [[1, 2, 3], [5, 4], [8], [9, 7], []]>
<tf.RaggedTensor [[b'So', b'long'], [b'thanks', b'for', b'your', b'food', b'fish'], []]>


In [86]:
# operations
print(tf.reduce_max(ragged, axis=0))   # maximum along row direction for each column
print(tf.concat([ragged, [[6],[6],[6],[6],[6]]], axis = 1))  # add same rank tensor along given axis
print(tf.tile(ragged, [2, 2]))  # expand the tensor along axis by duplicating items
print(tf.strings.substr(word_ragged, 1, 3))  # substring for starting index and end index
print(tf.map_fn(tf.math.square, ragged)) # map each item in tensor according to map function

tf.Tensor([9 7 3], shape=(3,), dtype=int32)
<tf.RaggedTensor [[1, 2, 3, 6], [5, 4, 6], [8, 6], [9, 7, 6], [6]]>
<tf.RaggedTensor [[1, 2, 3, 1, 2, 3], [5, 4, 5, 4], [8, 8], [9, 7, 9, 7], [],
 [1, 2, 3, 1, 2, 3], [5, 4, 5, 4], [8, 8], [9, 7, 9, 7], []]>
<tf.RaggedTensor [[b'o', b'ong'], [b'han', b'or', b'our', b'ood', b'ish'], []]>
<tf.RaggedTensor [[1, 4, 9], [25, 16], [64], [81, 49], []]>


In [ ]:
# We can use Python-style indexing to access specific slices of a ragged tensor.

In [83]:
times_two_plus_one = lambda x: x * 2 + 1
print(tf.map_fn(times_two_plus_one, ragged))

<tf.RaggedTensor [[3, 5, 7], [11, 9], [17], [19, 15], []]>


In [ ]:
# ragged tensors can be used in Keras model building layers
# It can also be converted to other tensors like Sparse tensor etc.

In [ ]:
# Sparse Tensor
"""
When working with tensors that contain a lot of zero values, it is important to
store them in a space- and time-efficient manner. Sparse tensors enable efficient
storage and processing of tensors that contain a lot of zero values.
"""

# creating sparse tensor:
# Construct sparse tensors by directly specifying their values, indices, and dense_shape.
"""
1. values: A 1D tensor with shape [N] containing all nonzero values.
2. indices: A 2D tensor with shape [N, rank], containing the indices of the nonzero values.
3. dense_shape: A 1D tensor with shape [rank], specifying the shape of the tensor.
"""

In [97]:
spt1 = tf.sparse.SparseTensor(indices=[[0, 3], [2, 4]],  # location of non-zero values
                      values=[10, 20],                   # non-zero values
                      dense_shape=[3, 10])               # dimension of tensor
spt1

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [98]:
# creating sparse from dense:
spt2 = tf.sparse.from_dense([[1, 0, 0, 8], [0, 0, 0, 0], [0, 0, 3, 0]])
print(spt2)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [0 3]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 8 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [99]:
# sparse to dense
st3 = tf.sparse.to_dense(spt1)
print(st3)

tf.Tensor(
[[ 0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]], shape=(3, 10), dtype=int32)


In [100]:
# Ragged vs Sparse tensor:
"""
A ragged tensor should not be thought of as a type of sparse tensor. In particular,
sparse tensors are efficient encodings for tf.Tensor that model the same data in a
compact format; but ragged tensor is an extension to tf.Tensor that models an
expanded class of data.
"""
ragged_x = tf.ragged.constant([["John"], ["a", "big", "dog"], ["my", "cat"]])
ragged_y = tf.ragged.constant([["fell", "asleep"], ["barked"], ["is", "fuzzy"]])
print(tf.concat([ragged_x, ragged_y], axis=1)) # rows of both ragged tensors has merged

<tf.RaggedTensor [[b'John', b'fell', b'asleep'], [b'a', b'big', b'dog', b'barked'],
 [b'my', b'cat', b'is', b'fuzzy']]>


In [101]:
sparse_x = ragged_x.to_sparse()
sparse_y = ragged_y.to_sparse()
sparse_result = tf.sparse.concat(sp_inputs=[sparse_x, sparse_y], axis=1)
print(tf.sparse.to_dense(sparse_result, ''))  # row of both sparse has just added together

tf.Tensor(
[[b'John' b'' b'' b'fell' b'asleep']
 [b'a' b'big' b'dog' b'barked' b'']
 [b'my' b'cat' b'' b'is' b'fuzzy']], shape=(3, 5), dtype=string)
