In [ ]:
# Variables

In [ ]:
import tensorflow as tf
import numpy as np
tf.version.VERSION

'2.12.0'

In [ ]:
# To see where your variables get placed
 # tf.debugging.set_log_device_placement(True)

In [3]:
# Tensorflow Variables
# A tf.Variable represents a tensor whose value can be changed by running ops on it. (mutable)
# It is the recommended way to represent shared, persistent state your program manipulates.
# Note: Higher level libraries like tf.keras use tf.Variable to store model parameters.

In [6]:
# Create a Variable:
tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
variable = tf.Variable(tensor)
variable

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [10]:
# Variables can be all kinds of types, just like tensors
# New values can be assigned to variables. Calling assign does not (usually) allocate
# a new tensor; instead, the existing tensor's memory is reused.
variable.assign([[9., 8.],[6.,3.]]) # same shape values can replace
variable  # here no new memory is created

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[9., 8.],
       [6., 3.]], dtype=float32)>

In [ ]:
# Note: We cannot reshape the variable

In [11]:
# Creating new variables from existing variables
# It will duplicates the backing tensors. Two variables will not share the same memory.
new_var = tf.Variable(variable)
print(new_var)
variable.assign([[1., 1.],[1.,3.]])
print(new_var)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[9., 8.],
       [6., 3.]], dtype=float32)>
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[9., 8.],
       [6., 3.]], dtype=float32)>


In [ ]:
# Lifecycle of Variables:
"""
In Python-based TensorFlow, tf.Variable instance have the same lifecycle as other
Python objects. When there are no references to a variable it is automatically deallocated.
"""
# Variable names are preserved when saving and loading models
# We can turn off gradients for a variable by setting trainable to false at creation.
const_var = tf.Variable(variable, trainable=False)

In [12]:
# For Computation including Variable and Tensors:
"""
For better performance, TensorFlow will attempt to place tensors and variables on
the fastest device compatible with its dtype. This means most variables are placed
on a GPU if one is available.
"""

# Also, It's possible to set the location of a variable or tensor on one device and
# do the computation on another device. This will introduce delay, as data needs to
# be copied between the devices.

with tf.device('CPU:0'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.Variable([[1.0, 2.0, 3.0]])

with tf.device('GPU:0'):
  # Element-wise multiply
  k = a * b

print(k)

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[ 1.  4.  9.]
 [ 4. 10. 18.]], shape=(2, 3), dtype=float32)


In [ ]:
# We can also do operations between Variables and Tensors which will give tensors